// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohbugduzkifavxzrgjdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oYnVnZHV6a2lmYXZ4enJnamRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTc5NjMsImV4cCI6MjA2MTczMzk2M30.iXWwPmlBJAWptXWrQaDvZZp88cvvgm7aXziUHBlg8io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);